### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by isp13** [Cpponelove/HSE_RPG#1]
HELP i am trying to run this game on macbook Mojave 10.14 but nothing happens in my android studio.

**Comment by Cpponelove** [comment]
Может ты нахуй пойдёшь,быдло ебаное

**Comment by isp13** [comment]
- firstly, be polite
-secondly, fix issue because your game does not work

**Comment by Cpponelove** [comment]
говна наверни сын говна на edited

**Comment by isp13** [comment]
overall, i want to mention that this application is dumping our memory while running like a virus

**Comment by Cpponelove** [comment]
хуй соси я тебе 100 репортов кинул мудила пендосская
